Repository LKW9/AMU_BE, pull requests merged in 2023-03, with the labels that each got.

#2 feat: Mongodb cluster connect
  .env
Labels: edit

#14 Wiki Folder
  src/amuwiki/amuwiki.controller.spec.ts
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.module.ts
  src/amuwiki/amuwiki.service.spec.ts
  src/amuwiki/amuwiki.service.ts
  src/app.module.ts
Labels: develop

#15 feat: Basic Login part built
  package-lock.json
  package.json
  src/app.module.ts
  src/user/dto/user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.schema.ts
  src/user/user.service.ts
Labels: develop, enhancement

#17 search test
  .gitignore
  monstache-config.toml
  package.json
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.module.ts
  src/amuwiki/amuwiki.service.ts
  src/amuwiki/dto/searchAmuwiki.dto.ts
  src/amuwiki/schema/amuwiki.schema.ts
  src/app.module.ts
  src/elasticsearch/elasticsearch.service.ts
  src/product/product.controller.spec.ts
  src/product/product.controller.ts
  src/product/product.module.ts
  src/product/product.schema.ts
  src/product/product.service.spec.ts
  src/product/product.service.ts
Labels: develop

#18 feat: Basic Login part built
  package-lock.json
  package.json
  src/amuwiki/amuwiki.controller.spec.ts
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.module.ts
  src/amuwiki/amuwiki.service.spec.ts
  src/amuwiki/amuwiki.service.ts
  src/amuwiki/dto/searchAmuwiki.dto.ts
  src/app.controller.spec.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/main.ts
Labels: develop, enhancement

#25 feat: Add method of sending verifying code to email to Signup part
  package-lock.json
  package.json
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.module.ts
  src/amuwiki/amuwiki.service.ts
  src/app.module.ts
  src/user/dto/verifyEmail.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: develop, edit, enhancement

#27 feat: Comparing verify code with email
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/user/dto/verifyEmailCode.dto.ts
  src/user/schemas/user.schema.ts
  src/user/schemas/verifiedEmail.schema.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: develop, database, enhancement

#29 feat: Rebuilding Sinup part using verify method
  src/user/dto/user.dto.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: develop, developEnd, database, enhancement

#31 feat: Rebuilding Login part
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: develop, edit, enhancement

#40 feat: Building Profile search part
  .eslintrc.js
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/profile/dto/basicProfile.dto.ts
  src/profile/dto/createProfile.dto.ts
  src/profile/dto/detailProfile.dto.ts
  src/profile/dto/editProfile.dto.ts
  src/profile/profile.controller.ts
  src/profile/profile.module.ts
  src/profile/profile.service.ts
  src/profile/schemas/profile.schema.ts
Labels: develop, edit

#41 feat: Building Profile creat part
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: develop, edit

#42 feat: Building Profile edit part
  src/app.module.ts
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: develop, edit

#45 feat: Building Authorization part
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
Labels: develop, edit, developEnd, enhancement

#46 feat: Building Membership withdrawl part
  package-lock.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/deleteuser.dto.ts
  src/user/user.service.ts
Labels: develop, edit, developEnd, enhancement

#50 Refactoring wiki file
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.service.ts
Labels: refactoring, enhancement

#51 Refactoring wiki file
  package.json
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.module.ts
Labels: refactoring, enhancement

#56 feat: Correcting the spelling error
  src/auth/auth.controller.ts
Labels: edit

#58 feat: Building Post create part
  src/app.module.ts
  src/post/dto/createPost.dto.ts
  src/post/post.controller.ts
  src/post/post.module.ts
  src/post/post.service.ts
Labels: develop

#59 feat: Building Post delete part
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: develop

#60 feat: Building Post edit part
  src/post/dto/editPost.dto.ts
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: develop

#65 feat: Refactoring user file
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: refactoring, developEnd

#66 feat: Refactoring auth file
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
Labels: refactoring, developEnd

#67 feat: error frofile image upload
  package-lock.json
  package.json
  src/profile/dto/basicProfile.dto.ts
  src/profile/dto/uploadProfile.dto.ts
  src/profile/profile.controller.ts
  src/profile/profile.module.ts
  src/profile/profile.service.ts
  src/profile/schemas/profile.schema.ts
Labels: bug

#71 feat: 2nd Refactoring post file
  src/post/dto/editPost.dto.ts
  src/post/post.controller.ts
  src/post/post.module.ts
  src/post/post.service.ts
Labels: refactoring, edit, developEnd, enhancement

#72 feat:change Profile
  package.json
  src/main.ts
  src/post/dto/editPost.dto.ts
  src/post/post.controller.ts
  src/post/post.module.ts
  src/post/post.service.ts
  src/profile/profile.controller.ts
  src/profile/profile.module.ts
  src/profile/profile.service.ts
  src/profile/schemas/profile.schema.ts
  src/user/schemas/user.schema.ts
Labels: develop, refactoring, edit, developEnd, enhancement

#73 Refactoring wiki file
  src/amuwiki/amuwiki.service.ts
Labels: developEnd, enhancement

#75 feat: 3rd Refactoring post file
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: refactoring, edit

#77 feat: Building Post's mypost part
  src/amuwiki/amuwiki.service.ts
  src/post/post.controller.ts
  src/post/post.module.ts
Labels: develop, refactoring, developEnd, database, databaseProblem

#79 feat: 4th Refactoring post file
  src/post/post.controller.ts
  src/post/post.module.ts
  src/post/post.service.ts
Labels: refactoring, edit

#87 feat: Retouching ReadMe
  README.md
Labels: develop

#88 feat: Retouching Readme
  README.md
Labels: develop

#89 feat: Composing Dockercompose-practice
  .dockerignore
  docker-compose.yml
  dockerfile
  elasticsearch.dockerfile
Labels: develop

#93 feat: Excluding the application of camel case.
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/post/post.controller.ts
  src/post/post.service.ts
  src/profile/dto/uploadProfile.dto.ts
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: edit

#95 feat: Excluding the application of camel case
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/profile/profile.module.ts
  src/profile/schemas/profile.schema.ts
  src/user/schemas/user.schema.ts
  src/user/schemas/verifiedEmail.schema.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: edit

#97 feat: Fixing docker-compose.yml and Filename
  docker-compose.yml
  elasticsearch.dockerfile
  monstache-config.toml
Labels: develop, refactoring, edit, enhancement

#98 Update auth.service.ts
  src/auth/auth.service.ts
Labels: edit

#100 feat:Testing application connected with dockercompose
  src/main.ts
  uploads/test.jpg
Labels: refactoring, edit

#102 Updating Amuwiki Search
  src/amuwiki/amuwiki.service.ts
Labels: enhancement

#105 feat: Changing contributors from 'nickname' to 'email'
  src/amuwiki/amuwiki.service.ts
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: develop, refactoring, edit, developEnd, database, enhancement, databaseProblem

#112 feat: 5th Refactoring post file
  src/amuwiki/amuwiki.service.ts
  src/post/dto/detailpost.dto.ts
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: refactoring, edit

#115 Refactoring Amuwiki Search
  src/amuwiki/amuwiki.controller.ts
  src/amuwiki/amuwiki.service.ts
Labels: refactoring

#117 feat:Refactoring Profile
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: refactoring

#119 feat: 6th Refactoring Post part
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: refactoring, edit

#121 feat: Refactoring Auth and User file
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: develop, refactoring, edit, developEnd, enhancement

#124 feat: Refactoring errorHandler
  src/auth/auth.service.ts
  src/user/user.service.ts
Labels: bugfix, refactoring, edit

#125 Update README.md
  README.md
Labels: edit

#130 feat:Refactoring Image Upload
  src/profile/profile.controller.ts
  src/profile/profile.service.ts
Labels: refactoring, edit

#131 feat: Building password retrieval and change functionality
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/changepassword.dto.ts
  src/auth/dto/verifyemail.dto.ts
  src/auth/dto/verifyemailcode.dto.ts
  src/user/user.module.ts
  src/user/user.service.ts
  uploads/Cat03.jpg
Labels: bug, develop, bugfix, refactoring, edit, developEnd, database, enhancement

#133 feat: Refactoring bug code
  src/user/user.service.ts
Labels: bug, develop, bugfix, refactoring, edit, developEnd

#135 feat: Changing Storage to Google cloud storage
  my-project-amu-b74433c069fd.json
  package-lock.json
  package.json
  src/profile/profile.module.ts
  src/profile/profile.service.ts
  src/profile/storage.module.ts
Labels: bug, develop, bugfix, refactoring, database, enhancement, databaseProblem

#139 feat:Updating Docker-compose.yml
  docker-compose.yml
Labels: enhancement

#141 Refactoring verifying email
  src/user/user.service.ts
Labels: bug, bugfix
